services:
  - type: web
    name: querydocs-api
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: "8000"
